version: "3.9"
services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "35432:5432"
    volumes:
      - ./db/pg_data:/var/lib/postgresql/data
    restart: always
